openapi: 3.0.0
info:
  title: Fondidita
  description: |-
    An API to handle a small restaurant app
  version: 1.0.11
externalDocs:
  description: Github repository of this project
  url: https://github.com/wayusei/FonDiDita
servers:
  - url: https://localhost:3000/
  - url: https://Customersstore3.swagger.io/api/v3
tags:
  - name: Customers
    description: Everything about Customers
  - name:  Sellers
    description: Everything about Sellers
  - name: Products
    description: Everything about Products
    
paths:
  /:
    post:
      tags: 
      - Customers
      summary: Inserts new Customers into database
      parameters:
      - $ref: '#/components/parameters/token'
      requestBody:
        content:
          application/json:
          - $ref: 'components/schemas/BodyCustomerPost'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: ''
      
  components:
    responses:
    parameters:
     token:
        in: header
        description: token
        required: true
    schemas:
      BodyCustomersPost:
        type: object
          properties:
            id:
              type: int
              description: Id
              example: 1
            username:
              type: string
              description: nombre de susuario
              example: user1
            email:
              type: string
              description: e-mail
              example: user1@mail.com
            password:
              type: string
              description: password
              example: abcd1234
            full_name:
              type: string
              description: Full name
              example: Juan Juanes
            billing_address:
              type: string
              description: Address
              example: Street 11
            default_shipping_address:
              type: string
              description: Default address fro shipping
              example: Street 22
            phone:
              type: string
              description: Phones
              example: 12345478
      ResCustomersPost:
        type: object
          properties:
          
            id:
              type: int
              description: Id
              
            username:
              type: string
              description: nombre de susuario
             
            email:
              type: string
              description: e-mail
             
            password:
              type: string
              description: password
             
            full_name:
              type: string
              description: Full name
              
            billing_address:
              type: string
              description: Address
              
            default_shipping_address:
              type: string
              description: Default address fro shipping
             
            phone:
              type: string
              description: Phones
             
              
              
  
        
      


  